webtalk_init -webtalk_dir D:/B.Tech/RTL_resources/verilog FPGA course Projects/Mini_Projects/Mini_Projects.sim/sim_1/behav/xsim/xsim.dir/UART_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Sep  8 02:38:24 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "448b8aa8-a2f8-4ec1-bbb5-dfda0932fb5d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "fc4c3e24d93c4c4694473af5426ec6e5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 5600H with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3294 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "7.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "11 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8124_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3644724455 -regid "" -xml D:/B.Tech/RTL_resources/verilog FPGA course Projects/Mini_Projects/Mini_Projects.sim/sim_1/behav/xsim/xsim.dir/UART_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/B.Tech/RTL_resources/verilog FPGA course Projects/Mini_Projects/Mini_Projects.sim/sim_1/behav/xsim/xsim.dir/UART_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/B.Tech/RTL_resources/verilog FPGA course Projects/Mini_Projects/Mini_Projects.sim/sim_1/behav/xsim/xsim.dir/UART_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
