# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ripple_carry_adder_4bit/ripple_carry_adder_4bit.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ripple_carry_adder_4bit || ORIG_REF_NAME==ripple_carry_adder_4bit} -quiet] -quiet

# IP: bd/ripple_carry_adder_4bit/ip/ripple_carry_adder_4bit_fa_0_0/ripple_carry_adder_4bit_fa_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ripple_carry_adder_4bit_fa_0_0 || ORIG_REF_NAME==ripple_carry_adder_4bit_fa_0_0} -quiet] -quiet

# IP: bd/ripple_carry_adder_4bit/ip/ripple_carry_adder_4bit_fa_0_1/ripple_carry_adder_4bit_fa_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ripple_carry_adder_4bit_fa_0_1 || ORIG_REF_NAME==ripple_carry_adder_4bit_fa_0_1} -quiet] -quiet

# IP: bd/ripple_carry_adder_4bit/ip/ripple_carry_adder_4bit_fa_0_2/ripple_carry_adder_4bit_fa_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ripple_carry_adder_4bit_fa_0_2 || ORIG_REF_NAME==ripple_carry_adder_4bit_fa_0_2} -quiet] -quiet

# IP: bd/ripple_carry_adder_4bit/ip/ripple_carry_adder_4bit_fa_0_3/ripple_carry_adder_4bit_fa_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ripple_carry_adder_4bit_fa_0_3 || ORIG_REF_NAME==ripple_carry_adder_4bit_fa_0_3} -quiet] -quiet

# IP: bd/ripple_carry_adder_4bit/ip/ripple_carry_adder_4bit_xlslice_0_0/ripple_carry_adder_4bit_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ripple_carry_adder_4bit_xlslice_0_0 || ORIG_REF_NAME==ripple_carry_adder_4bit_xlslice_0_0} -quiet] -quiet

# IP: bd/ripple_carry_adder_4bit/ip/ripple_carry_adder_4bit_xlslice_0_1/ripple_carry_adder_4bit_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ripple_carry_adder_4bit_xlslice_0_1 || ORIG_REF_NAME==ripple_carry_adder_4bit_xlslice_0_1} -quiet] -quiet

# IP: bd/ripple_carry_adder_4bit/ip/ripple_carry_adder_4bit_xlslice_0_2/ripple_carry_adder_4bit_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ripple_carry_adder_4bit_xlslice_0_2 || ORIG_REF_NAME==ripple_carry_adder_4bit_xlslice_0_2} -quiet] -quiet

# IP: bd/ripple_carry_adder_4bit/ip/ripple_carry_adder_4bit_xlslice_0_3/ripple_carry_adder_4bit_xlslice_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ripple_carry_adder_4bit_xlslice_0_3 || ORIG_REF_NAME==ripple_carry_adder_4bit_xlslice_0_3} -quiet] -quiet

# IP: bd/ripple_carry_adder_4bit/ip/ripple_carry_adder_4bit_xlslice_0_4/ripple_carry_adder_4bit_xlslice_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ripple_carry_adder_4bit_xlslice_0_4 || ORIG_REF_NAME==ripple_carry_adder_4bit_xlslice_0_4} -quiet] -quiet

# IP: bd/ripple_carry_adder_4bit/ip/ripple_carry_adder_4bit_xlslice_1_0/ripple_carry_adder_4bit_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ripple_carry_adder_4bit_xlslice_1_0 || ORIG_REF_NAME==ripple_carry_adder_4bit_xlslice_1_0} -quiet] -quiet

# IP: bd/ripple_carry_adder_4bit/ip/ripple_carry_adder_4bit_xlslice_3_0/ripple_carry_adder_4bit_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ripple_carry_adder_4bit_xlslice_3_0 || ORIG_REF_NAME==ripple_carry_adder_4bit_xlslice_3_0} -quiet] -quiet

# IP: bd/ripple_carry_adder_4bit/ip/ripple_carry_adder_4bit_xlslice_2_0/ripple_carry_adder_4bit_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ripple_carry_adder_4bit_xlslice_2_0 || ORIG_REF_NAME==ripple_carry_adder_4bit_xlslice_2_0} -quiet] -quiet

# IP: bd/ripple_carry_adder_4bit/ip/ripple_carry_adder_4bit_xlconcat_0_0/ripple_carry_adder_4bit_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ripple_carry_adder_4bit_xlconcat_0_0 || ORIG_REF_NAME==ripple_carry_adder_4bit_xlconcat_0_0} -quiet] -quiet

# XDC: bd/ripple_carry_adder_4bit/ripple_carry_adder_4bit_ooc.xdc
