@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Sep 05 17:53:29 +0530 2024
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim barrel_shifter_8_bit_wrapper_behav -key {Behavioral:sim_1:Functional:barrel_shifter_8_bit_wrapper} -tclbatch barrel_shifter_8_bit_wrapper.tcl -protoinst "protoinst_files/barrel_shifter_8_bit.protoinst" -protoinst "protoinst_files/BCD_7_seg_display.protoinst" -protoinst "protoinst_files/MUX_4_1.protoinst" -protoinst "protoinst_files/MUX_4_1.protoinst" -protoinst "protoinst_files/MUX_4_1.protoinst" -protoinst "protoinst_files/MUX_4_1.protoinst" -protoinst "protoinst_files/barrel_shifter_4_bit.protoinst" -protoinst "protoinst_files/MUX_4_1.protoinst" -protoinst "protoinst_files/ripple_carry_adder_4bit.protoinst" -protoinst "protoinst_files/shift_reg.protoinst" -protoinst "protoinst_files/Mux_8_1.protoinst" -log simulate.log"
call xsim  barrel_shifter_8_bit_wrapper_behav -key {Behavioral:sim_1:Functional:barrel_shifter_8_bit_wrapper} -tclbatch barrel_shifter_8_bit_wrapper.tcl -protoinst "protoinst_files/barrel_shifter_8_bit.protoinst" -protoinst "protoinst_files/BCD_7_seg_display.protoinst" -protoinst "protoinst_files/MUX_4_1.protoinst" -protoinst "protoinst_files/MUX_4_1.protoinst" -protoinst "protoinst_files/MUX_4_1.protoinst" -protoinst "protoinst_files/MUX_4_1.protoinst" -protoinst "protoinst_files/barrel_shifter_4_bit.protoinst" -protoinst "protoinst_files/MUX_4_1.protoinst" -protoinst "protoinst_files/ripple_carry_adder_4bit.protoinst" -protoinst "protoinst_files/shift_reg.protoinst" -protoinst "protoinst_files/Mux_8_1.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
